name: Scrape GitHub Models
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run scraper
      run: |
        python script.py -f json -o models.json
        
    - name: Check for changes
      id: git-check
      run: |
        git diff --exit-code models.json || echo "changes=true" >> $GITHUB_OUTPUT

    - name: Commit and push if changed
      if: steps.git-check.outputs.changes == 'true'
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add models.json
        timestamp=$(date -u)
        git commit -m "Latest models data: ${timestamp}"
        git push